tengstrom_configuration.settings:
  type: config_object
  label: 'Tengstr√∂m Configuration settings'
  mapping:
    logo_uuid:
      type: uuid
      label: 'Uuid to logo in managed file table'
    logo_email_uuid:
      type: uuid
      label: 'Uuid to e-mail logo in managed file table'
    favicon_uuid:
      type: uuid
      label: 'Uuid to favicon in managed file table'
